global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
#rule_files:
#  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
#
#  - job_name: 'service2-1'
#    scrape_interval: 10s
#    metrics_path: '/actuator/prometheus'
#    honor_labels: true
#    static_configs:
#      - targets: ['service2-1:8080']

  - job_name: eureka-discovery
    scrape_interval: 15s
    scrape_timeout: 15s
    eureka_sd_configs:
      - server: http://eureka:8761/eureka
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
      - source_labels: [__meta_eureka_app_instance_metadata_metrics_path]
        target_label: __metrics_path__
      - source_labels: [__address__]
        target_label: instance
